### ISSUE TITLE
Provide pkg-config file

### ISSUE THREAD

**Issue by tobiasdiez** [graph-algorithms/edge-addition-planarity-suite#122]
It would be nice to distribute a [pkg-config file](https://people.freedesktop.org/~dbn/pkg-config-guide.html) so that the library can be found more easily on the system by other programs/libraries.

**Comment by wbkboyer** [comment]
Hello @tobiasdiez ! This is a great suggestion; could you give me some more context on your use-case (e.g. are you trying to find headers for and link with `libplanarity`)? This would help us understand how to test that we are producing a file that will solve your use case! 🎉 

I'd like to try to use the existing autotools pipline to generate the `.pc` file; [this](https://www.linuxquestions.org/questions/programming-9/generating-pkg-config-file-in-makefile-4175683854/) forum post links to how the [`LFSToolkit`](https://github.com/KeithDHedger/LFSDesktopProject/tree/master/LFSToolKit) solves this with their [`Makefile.am`](https://github.com/KeithDHedger/LFSDesktopProject/blob/master/LFSToolKit/Makefile.am) and [`lfstk.pc.in`](https://github.com/KeithDHedger/LFSDesktopProject/blob/master/LFSToolKit/lfstk.pc.in), which aligns with the general framework supplied in [this](https://lists.freedesktop.org/archives/pkg-config/2007-August/000218.html) mailing list post. Could you also let me know where you expect the `.pc` file to be placed for you to consume?

Thank you again, and looking forward to getting this working with you!

**Comment by tobiasdiez** [comment]
Yes, we link against planarity (https://github.com/search?q=repo%3Asagemath%2Fsage+planarity&type=code&p=1) and currently use `AC_CHECK_HEADER([planarity/planarity.h]) / AC_CHECK_LIB` (make) and `find_library('planarity')` (meson) to detect if its installed. We would like to switch to `PKG_CHECK_MODULES` / `dependency` which uses pkg-config to detect (and determine linker + include dirs etc). To test: install planarity and then `pkg-config --cflags planarity (or libplanarity)` and verify that it prints the correct include directory.

Here is another example: https://github.com/miguelmarco/libbraiding/pull/4

**Comment by wbkboyer** [comment]
Hey @tobiasdiez ! I created #125 , and verified that `pkg-config` can find `libplanarity`. Please let me know if there's any additional macros I should be calling or variables that need to be defined!

On a related note, due to the source code reorganization undertaken in #91 , I think you'll have to update two files:

* [`src/sage/graphs/planarity.pyx`](https://github.com/sagemath/sage/blob/8a972c4d39ebd61b39885dde30e6b02db9015a89/src/sage/graphs/planarity.pyx#L4) - `cdef extern from "planarity/graph.h":` ==> `cdef extern from "planarity/graphLib/graph.h":`
* [`build/pkgs/planarity/spkg-configure.m4`](https://github.com/sagemath/sage/blob/8a972c4d39ebd61b39885dde30e6b02db9015a89/build/pkgs/planarity/spkg-configure.m4#L4) - `AC_CHECK_HEADER([planarity/planarity.h],` ==> `AC_CHECK_HEADER([planarity/planarityApp/planarity.h],`

@john-boyer-phd has some additional insight into more comprehensive checks that can be done in `planarity.pyx` to ensure the right endpoints are exposed!

**Comment by wbkboyer** [comment]
Hey @tobiasdiez ! I wanted to give you a quick update: I need to take some time to further investigate the workings of the autotools pipeline to make sure the libraries and headers are being installed in places that make sense for consumers such as sagemath... Could you give me a timeline for when you folks are switching over to the `pkg-config`-driven dependency checking? This will give us a clamp on when we need to get the 4.0 release out the door!

**Comment by tobiasdiez** [comment]
There are no constraints from our side. Directly checking for the header works, it's just that pkg-config is a bit more convenient and robust. So whenever you ship the pkg-config info, we will use it - but no hurry.
