### ISSUE TITLE
The windows version runtime displays the lack of libmingwex-2.dll.

### ISSUE THREAD

**Issue by lichengzhang1** [graph-algorithms/edge-addition-planarity-suite#13]
When I download [planarity-3.0.2.0.WindowsExe.zip](https://github.com/graph-algorithms/edge-addition-planarity-suite/releases/download/Version_3.0.2.0/planarity-3.0.2.0.WindowsExe.zip), I try to run _planarity.exe_. But the following sentence is displayed.

- The program can't start because libmingwex-2.dll is missing from your computer. Try reinstalling the program to fix this problem.

First I only found _libmingwex-0.dll_ in my computer.  
 
I can't find libmingwex-2.dll  on the Internet. If I rename libmingwex-0.dll to libmingwex-2.dl and copy it to the same directory as the exe file, another error (Entry Point Not Found) occurs.

**Comment by john-boyer-phd** [comment]
Thank you very much for bringing up this issue. The fastest way to get you up and running while this problem is being addressed is to recommend that you switch to the 3.0.0.5 version for now, which is also downloadable from the Releases. Subsequent versions are compiled with a more recent version of mingw that creates executables that dynamically link to the standard library. I'll be looking into what mingw allows to be redistributed and if there are any other DLLs now needed, and then repackage 3.0.2.0 once that is known. In the meantime, I've just tested 3.0.0.5 on a machine that has never had mingw on it, so that should work for you for now.

**Comment by john-boyer-phd** [comment]
I've updated the 3.0.2.0 release with a new windows zip file that now contains the libmingwex-2.dll file. Based on testing with a machine with no MinGW installed, there are no other DLLs needed to run the precompiled version. Although you won't need them, I noted that the 3.0.1.1 and 3.0.1.0 releases had the same issue with the precompiled version, so those have been patched as well. Since the precompiled version now appears to work on non-MinGW machines, I'll close this issue. Please let me know if you have any other issues, and thank you again for taking the time to report this issue.
